GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "marion",
   "password": "toto",
   "email": "marion@gmail.com",
   "mobile" : "02525875"
}