GET http://localhost:8080/users

###
GET http://localhost:8080/users/b4a662ae-5e0d-4eff-8ed6-0fb3bdb3946f

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "Marion",
    "password": "!salut65",
    "email": "marion.hourdou@hotmail.fr",
    "mobile" : "08 19 96 29 86"
}